services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3S\T3sbootstrapGrid\:
    resource: '../Classes/*'

  T3S\T3sbootstrapGrid\Backend\Preview\T3sGridPreviewRenderer:
    public: true
